@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Stripe TOS</div>

                <div class="panel-body">
                  <h2>Stripe Connect Platform Agreement</h2>
This Stripe Connect Platform Agreement (“Connect Platform Agreement”) is an agreement between the legal entity (including sole proprietors) that you identified on the registration page (“you”) and Stripe. Your integration and use of Stripe Connect with your platform (“Platform”) is subject to your acceptance of the terms and conditions of this Connect Platform Agreement and the Stripe Services Agreement. By integrating and using Stripe Connect, you expressly agree to the terms and conditions of this Connect Platform Agreement, the Stripe Services Agreement, and any updates or modifications to either of those documents made from time to time by Stripe.

We use a number of defined terms in this Connect Platform Agreement. The products and services that you provide through your Platform, regardless of whether or not fees are charged, are referred to as “Platform Services”. Examples of Platform Services that you may agree to provide are web development or hosting services, customer service, processing of refunds, and the handling of consumer complaints. Your agreement with your users for the provision of the Platform Services is “Your User Agreement”, and your users are “Platform Merchants” until they have a Stripe Account that has onboarded to your Platform via Stripe Connect, at which point they become “Connected Accounts”. Actions submitted by or on behalf of Connected Accounts using Stripe Connect are referred to as “Activity”, and this includes the communication of information about Transactions (including Charges) and Refunds, adjustments, the handling of Disputes (including chargebacks), as well as other features as described in the Stripe Connect documentation. “Connected Account Data” refers to data about Connected Accounts, Activity on their Stripe Accounts, and their Transactions. For other capitalized terms not defined in this Connect Platform Agreement (either in-line or by hyperlink), the applicable definitions are set out in the Stripe Services Agreement.

You represent to Stripe that all of the information you provide to us is accurate and complete, and that you are authorized to agree to this Connect Platform Agreement.
<br>
1. Relationship to Other Agreements
Please read this Connect Platform Agreement carefully. This Connect Platform Agreement contains terms and conditions relating to your use of the features of Stripe Connect. This Connect Platform Agreement supplements the Stripe Services Agreement, which generally governs your use of the Services, and which is incorporated into this Connect Platform Agreement by reference. To the extent that there is a conflict between the Stripe Services Agreement and this Connect Platform Agreement related to Stripe Connect, this Connect Platform Agreement will prevail. Nothing in this Connect Platform Agreement alters the terms and conditions of the Stripe Services Agreement as they apply to your use of the Services for your own purposes (such as to receive payment for goods or services you provide).
<br>
2. Stripe Connect — Your Platform
Stripe Connect allows you to integrate the Services into your Platform. For example, you may use Stripe Connect to enable your Connected Accounts to accept payments for goods and services, or charitable or campaign donations, via your Platform. You may conduct Activity on behalf of your Connected Accounts, provided that you do so in accordance with this Connect Platform Agreement and Your User Agreement. You must ensure that you clearly and prominently explain to Connected Accounts the nature of the Platform Services and the Activity that you will conduct on their behalf.

Stripe has a direct contractual relationship with each Connected Account and provides Services directly to each Connected Account. Connected Accounts may choose to use the Services outside of their relationship with you.

You consent to Stripe’s disclosure of information about you and your Platform to Financial Services Providers, Payment Method Providers and Stripe’s service providers to facilitate the provision of Stripe Connect and Services to you and to the Connected Accounts. You also affirm that you have obtained all necessary rights and consents under applicable law to disclose to Stripe — or allow Stripe to collect, use, retain, and disclose — any information that you provide to us or authorize us to collect, including information that we may collect directly using cookies or other similar means. For more information regarding Stripe’s use of data, please review Stripe’s Privacy Policy.
<br>
3. Your Obligations
a. Agreements with Connected Accounts: Your User Agreement must explain the Platform Services, how you access and use Connected Account Data, and the Activity that you may perform. Your User Agreement must also give you clear authorization to perform the Platform Services, and to communicate the Connected Account Data to Stripe. Stripe is not responsible to your Connected Accounts for any Platform Services you provide — you are solely responsible for providing Platform Services to Connected Accounts as described in Your User Agreement. You may only engage in Activity for a Connected Account to the extent that you are doing so on behalf of the Connected Account, in accordance with the authority granted to you under Your User Agreement.

b. Activity: You are responsible for any Activity initiated by you, on your behalf, or using your credentials, on any Connected Account either through the Stripe dashboard or through Stripe Connect. Likewise, where either Stripe or a Connected Account incurs any losses based on unauthorized Activity initiated by you, or your employees, or your agents, you will be financially liable for such losses. Stripe may deduct such losses from your Stripe Account, or require you to immediately pay such losses to Stripe.

c. Compliance: You will at all times comply with all applicable laws and regulations, payment network rules (including the Network Rules), agreements with third parties that are binding on you, and this Connect Platform Agreement.

d. Instant Payouts: Depending on your location and the location of your Connected Accounts, you may be able to offer your Connected Accounts the ability to receive payment processing proceeds via accelerated settlement into a bank account linked to a Connected Account’s debit card (“Instant Payout”). When Instant Payouts is used, Stripe will attempt to settle payment processing proceeds within minutes of receiving the payout request. Prior to enabling an Instant Payout, you must determine, using the Stripe APIs, whether or not same-day availability of funds is enabled for the debit card by the card-issuing bank. If same-day funds availability is not enabled, you may only activate the Instant Payout if you have clearly and conspicuously disclosed this fact to the Connected Account. Your marketing of the Instant Payout functionality to Connected Accounts must clearly and conspicuously disclose the fees (if any) you intend to apply for Instant Payouts, as well as the fact that, for certain recipient banks, some Instant Payouts may not settle within minutes, and instead may take longer to be credited to the relevant bank account.

e. Limitations: You and Stripe are independent entities, and this Connect Platform Agreement does not create any partnership, agency, or employment relationship between you and Stripe, or the employees or agents of either party. You may not, and may not attempt to, make any representation, warranty or commitment on behalf of Stripe. You may not use any Stripe logo, or trade or service mark in a manner inconsistent with the Stripe Marks Usage Agreement.

You may not use Stripe Connect: (a) to access any Connected Account Data or conduct any Activity, or attempt to do either, for which a Connected Account has not given you express authorization or for which such authorization has been withdrawn; (b) for any fraudulent, unlawful, deceptive, or abusive purposes, or in any manner harmful to, or intended to harm, a Connected Account, Stripe, or any third party; or (c) to circumvent Stripe’s intended limitations for any feature of Stripe Connect or in a manner inconsistent with the Stripe Connect documentation.

f. Data Protection: You may only use Stripe Connect and Connected Account Data consistent with this Connect Platform Agreement. You will have a privacy policy that tells Connected Accounts what Connected Account Data you access and how you will use, display, or transfer that Connected Account Data. You will include a prominent link to your privacy policy and to the Stripe Privacy Policy in Your User Agreement. You will obtain consent from Connected Accounts before using Connected Account Data for any purpose other than providing Platform Services. You will use all reasonable efforts to protect and secure Connected Account Data from unauthorized use or disclosure, and will promptly notify Stripe where Connected Account Data is accessed or disclosed without permission.
<br>
4. Onboarding Connected Accounts
Stripe Connect provides various mechanisms for you to onboard Connected Accounts, as described in the Stripe Connect documentation. You are solely responsible for the selection of your onboarding mechanism for Connected Accounts, which may include assisting with the creation of a Stripe Account or integrating an existing Stripe Account with your Platform. Regardless of the onboarding and integration mechanism that you select, you must always take all reasonable steps to ensure that your Connected Accounts do not use Services in violation of the Stripe Connected Account Agreement or for any activity that is expressly prohibited, including those activities listed at Prohibited Businesses List.

Please read the following sections carefully prior to selecting the option that is appropriate for your business when onboarding Connected Accounts. Selection of the manner of onboarding and integration impacts your liability for Activity on the Connected Accounts. Some onboarding options have limited availability, and the availability of these options for your Platform will depend on your location and the location of your Connected Accounts.

a. Standard (formerly “Standalone”): Your customers may already have a Stripe Account but want to utilize Platform Services, or they may want to create a Stripe Account to use with your Platform. In these cases, once created, Connected Accounts will have the ability to add or remove access to your Platform through the Stripe dashboard. Each Connected Account must agree to the Stripe Connected Account Agreement prior to using their Connected Account on your Platform.

Where Connected Accounts are created or connected to your Platform through standard onboarding, you will have access to some of the Connected Account Data and may initiate Activity in accordance with Your User Agreement. Where the Connected Account does not have an existing Stripe Account, you will be able to prepopulate Connected Account Data prior to activation of the Connected Account. Stripe may also require you to collect and provide additional Connected Account Data to validate a Connected Account. You are responsible for ensuring the accuracy of any Connected Account Data you prepopulate or provide as part of this process. The Connected Account is responsible for Connected Account Data provided by the Connected Account directly to Stripe as part of the standard onboarding process.

Once a Connected Account goes through the standard onboarding process, you understand and agree that you are solely responsible for use of any Connected Account Data accessed and any Activity performed, and for any inaccurate or incomplete information provided to Stripe, by you, your employees, or your agents. A Connected Account may terminate the integration with your Platform at any time upon notice to Stripe.

For a Connected Account onboarded using standard onboarding, except where expressly stated in the Stripe Connected Account Agreement, the Connected Account is responsible and liable to Stripe for all Transactions (including Charges), Disputes, Refunds, Claims, fines, or use of the Services in a manner prohibited under the Stripe Connected Account Agreement.

b. Custom (formerly “Managed”): Using custom onboarding, you may use Stripe Connect to create Stripe Accounts for Connected Accounts. Where Connected Accounts go through custom onboarding, you are responsible for ensuring Connected Account Data regarding the Connected Accounts is passed to Stripe.

Stripe may decline to create a Stripe Account for a Connected Account or limit the functionality available to a Connected Account until Stripe is satisfied that it has received sufficient information about the Connected Account. You are responsible for the accuracy and completeness of any information about Connected Accounts provided to Stripe as part of the onboarding process. Connected Accounts created through custom onboarding will not have access to the Stripe dashboard.

You are solely responsible for ensuring that each Connected Account expressly agrees to comply with the Stripe Connected Account Agreement. You must ensure that Connected Accounts agree to the Stripe Connected Account Agreement in a manner that clearly evidences their acceptance and makes clear that Stripe is providing Services to them subject to the Stripe Connected Account Agreement. You must ensure that each Connected Account has an opportunity to review the Stripe Connected Account Agreement prior to acceptance, that the Connected Account’s acceptance is sufficient under applicable law (including by ensuring that the person agreeing on behalf of the Connected Account is of suitable legal age and is authorized to bind the Connected Account), and that such acceptance is confirmed, recorded, and can be audited. The Stripe Connect documentation describes the information that must be provided to Stripe in order to create a Connected Account through custom onboarding. Stripe may require that you provide additional information as part of the custom onboarding process, and may require you to alter the acceptance process for the Stripe Connected Account Agreement if we believe that the process is not consistent with applicable law, industry standard practices, or Stripe’s standards. Stripe may at any time require you to demonstrate your compliance with the requirements of this paragraph, including by providing evidence that acceptance of the Stripe Connected Account Agreement has been appropriately obtained and recorded.

c. Express: Using express onboarding, you can use a set of pre-built, co-branded user interface components to create your own onboarding experience for Connected Accounts. Connected Accounts created using express onboarding provide information directly to Stripe and may access a Stripe-hosted dashboard to see their payments history and identifying information.

For Connected Accounts created using custom or express onboarding, except as expressly provided in this Connect Platform Agreement, you understand and agree that you are responsible and liable to Stripe for all Activity on the Connected Accounts, whether initiated by you or not (including all Transactions, Disputes, Refunds, Reversals, Claims, fines associated with such Activity, and use of the Services in a manner prohibited under this Connect Platform Agreement or the Stripe Connected Account Agreement). Stripe may attempt to collect any amounts owed from Connected Accounts prior to collecting such amounts from you, however you remain directly liable to Stripe for any of the foregoing, and Stripe may debit these amounts from your Stripe Account or Payout Account. In addition, you are liable for any inaccurate or incomplete information provided to Stripe as part of the provisioning of Connected Accounts.
<br>
5. Underwriting and Screening
Stripe may require that you establish certain criteria for accepting Connected Accounts consistent with Stripe’s programs for underwriting and screening Connected Accounts (“Underwriting Policies”). Stripe has ultimate discretion regarding its underwriting, risk and compliance decisions, including any decision of whether to provide Services to any Connected Account. Stripe reserves the right to suspend or terminate provision of Services to any Connected Account at any time if Stripe determines that the Connected Account’s activities (a) violate Stripe’s Underwriting Policies or the Stripe Connected Account Agreement; (b) are listed on the Prohibited Businesses List; or (c) otherwise reflect negatively on the brand or reputation of Stripe, a Financial Services Provider, or a Payment Method Provider.

To the extent that you become aware of a Connected Account being engaged in any fraudulent, unlawful, deceptive or abusive activity, you must promptly notify Stripe. Once notified by you, Stripe will use commercially reasonable efforts to promptly determine whether to terminate or suspend any such account’s access to the Services.
<br>
6. Connect Pricing and Platform Fees
Except as expressly agreed upon in writing between you and Stripe, the pricing applicable to your Platform for the Services and Stripe Connect is described on Stripe’s pricing page, as may be amended from time to time. All fees charged by Stripe will be reflected in your Stripe dashboard. Stripe may deduct fees from your Stripe Account balance and from the Stripe Account balances of your Connected Accounts. Fees may be applied on a per transaction basis, or aggregated over a period of time, as described in your Stripe dashboard.

You are solely responsible for communicating any use, recurring, or application fees charged to Connected Accounts for their use of Platform Services (“Platform Fees”) and you must clearly communicate any Platform Fees to Connected Accounts prior to imposing such fees.
<br>
7. Indemnification
In addition to indemnification obligations under the Stripe Services Agreement, you agree to defend, indemnify, and hold harmless Stripe, Financial Services Providers, Payment Method Providers, and their respective employees and agents (each a “Disclaiming Entity”) from and against any claim, suit, demand, loss, liability, damage, action, or proceeding arising out of or relating to (a) your breach of any provision of this Connect Platform Agreement; (b) any disputes between you and Connected Accounts, including those arising from use of Connected Account Data or Activity by you, your employees, or your agents, whether for you or a Connected Account; or (c) your use of Stripe Connect in a manner that is illegal or inconsistent with the Stripe Connect documentation.

Where a Connected Account was created as part of a custom or express onboarding process, you also agree to defend, indemnify, and hold harmless all Disclaiming Entities from and against any claim, suit, demand, loss, liability, damage, action, or proceeding arising out of or relating to (d) Activity on the Connected Account, whether initiated by you or not (including all Transactions, Disputes, Refunds, Reversals, Claims, fines associated with such Activity, or use of the Services in a manner prohibited under this Connect Platform Agreement or the Stripe Connected Account Agreement); (e) any inaccurate or incomplete information provided to Stripe as part of the onboarding of the Connected Account; and (f) for custom onboarding, your failure to acquire binding acceptance of the Stripe Connected Account Agreement from any Connected Account.

Stripe agrees to defend, indemnify, and hold you harmless from and against any claim, suit, demand, action, or proceeding instituted by a non-affiliated third party to this Connect Platform Agreement to the extent that such arises out of Stripe Connect infringing the third party’s intellectual property rights.
<br>
8. Representations and Warranties
In addition to the representations and warranties of the Stripe Services Agreement, you represent and warrant to Stripe that you will (a) obtain authorization from the Connected Account for all Activity initiated on its behalf, and for the use of any Connected Account Data obtained through or used with Stripe Connect, by you, your employees, and your agents; (b) dutifully comply with the onboarding obligations described in this Connect Platform Agreement; and (c) not use Stripe Connect or knowingly permit the use of Services by Connected Accounts in a manner that is fraudulent, unlawful, deceptive or abusive.

To the maximum extent permitted by law, except as expressly provided in this Connect Platform Agreement, Stripe provides Stripe Connect to you on an “as is” “as available” basis, without any warranties, express, implied, or statutory.
<br>
9. Limitations of Liability
Stripe is not responsible for and disclaims all liability for your, your employees’, and your agents’ (a) acts or omissions in providing Platform Services to your Platform Merchants (including Connected Accounts), which includes delivery of goods or services to your Platform Merchants’ customers or any other third parties, or properly describing Platform Services; (b) compliance with applicable laws and obligations related to your offering or providing Platform Services; and (c) providing customer service, notifications, receipts, handling refunds or consumer complaints, or taking other actions related the Platform Service.

In no event will a Disclaiming Entity be liable for any lost profits, or any indirect, punitive, incidental, special, consequential, or exemplary damages arising out of, in connection with, or relating to this Connect Platform Agreement or Stripe Connect, including the use of, inability to use, or unavailability of Stripe Connect or the Services.

The Disclaiming Entities have no liability or responsibility for any (a) personal injury or property damage, of any nature whatsoever, resulting from use of Stripe Connect or the Services; (b) damage, loss, or injury resulting from hacking, tampering, or other unauthorized access to, or use of, Stripe Connect, including any unauthorized access to or use of third-party servers used in connection with Stripe Connect or the Services and/or any personal information stored therein; (c) interruption or cessation of Stripe Connect; (d) software bugs, viruses, trojan horses, or other harmful code that may be transmitted to or through Stripe Connect; (e) errors, inaccuracies, or omissions of information, or any damages or losses incurred as a result of such errors inaccuracies or omissions, resulting from the use of Stripe Connect; (f) information that is transmitted using Stripe Connect that is defamatory, offensive, or illegal; and/or (g) conduct of any third party.

Without limiting the foregoing provisions of this Section 9, the Disclaiming Entities’ cumulative liability to you in connection with Stripe Connect (including under this Connect Platform Agreement) will be limited to direct damages and in all events will not exceed in the aggregate the amount of fees paid by you to Stripe during the three (3) month period immediately preceding the event giving rise to the claim for liability.

This limitation of liability section applies to the maximum extent permitted by law, and applies regardless of the legal theory on which the claim is based, including contract, tort (including negligence, product liability, or otherwise), strict liability, or any other basis. The limitations apply even if the Disclaiming Entities have been advised of the possibility of such damage.
<br>
10. Other General Legal Terms
a. Term, Termination, and the Effects of Termination: The term of this Connect Platform Agreement will begin when you register your Platform with Stripe and will end when terminated by you or by Stripe as described in this Connect Platform Agreement. You may terminate this Connect Platform Agreement at any time by providing notice to Stripe and immediately ceasing your use of Stripe Connect. However, if you commence using Stripe Connect again after such notice, you will be considered to have consented to this Connect Platform Agreement again. Stripe may terminate this Connect Platform Agreement (a) if you are in breach of this Connect Platform Agreement and fail to cure the breach upon 30 days’ notice by Stripe (such notice only being required if curing the breach is feasible); (b) upon 120 days’ notice for any reason. Stripe may also terminate this Connect Platform Agreement immediately if you are the subject of any voluntary or involuntary bankruptcy or insolvency petition or proceeding, or if Stripe determines that you are engaged in activity that fails to comply with applicable law or causes a significant risk of reputational harm to Stripe.

Sections 7 through 10 and all provisions giving rise to continuing obligations (including Section 3.e.) will survive termination of this Connect Platform Agreement. As stated above, the Stripe Services Agreement governs your use of Services, so the termination of this Connect Platform Agreement will not immediately trigger termination of the Stripe Services Agreement. All obligations in the Stripe Services Agreement will only be terminated in accordance with the terms and conditions of the Stripe Services Agreement. Termination of the Stripe Services Agreement will cause this Connect Platform Agreement to automatically terminate.

b. Governing Law, Disputes, and Interpretation: The provisions of the applicable Stripe Services Agreement governing applicable law (jurisdiction), location of suits and disputes (venue), and any method for dispute resolution are incorporated into this Connect Platform Agreement by reference. Headings are included for convenience only, and should not be considered in interpreting this Connect Platform Agreement. No provision of this Connect Platform Agreement will be construed against any party on the basis of that party being the drafter. Unless stated otherwise, the word “including” means “including, without limitation”. This Connect Platform Agreement does not limit any rights of enforcement that Stripe may have under trade secret, copyright, patent, or other laws. Stripe’s delay or failure to assert any right or provision under this Connect Platform Agreement does not constitute a waiver of such right or provision. No waiver of any term of this Connect Platform Agreement will be deemed a further or continuing waiver of such term or any other term.

c. Stripe Services Agreement: The Stripe Services Agreement version incorporated into this Connect Platform Agreement is the version applicable to your Stripe Account jurisdiction. If the name of your jurisdiction does not appear in the title of the page accessible via this Stripe Services Agreement link, please contact us and we will provide you with the correct link.

d. Taxes: Stripe’s fees are exclusive of any applicable sales or value-added tax, except as expressly stated to the contrary. You have sole responsibility for determining what, if any, taxes or fees apply in connection with your, and your Connected Accounts’, use of Stripe Connect and the Services (“Taxes”). You are responsible for assessing, collecting, reporting, and remitting Taxes to the appropriate tax and revenue authorities. If Stripe is required to withhold any Taxes, Stripe may deduct such Taxes from amounts otherwise owed and pay them to the appropriate taxing authority. If you are exempt from payment of such Taxes, you must provide Stripe with an original certificate that satisfies applicable legal requirements attesting to your tax-exempt status. You must provide accurate information regarding your tax affairs as reasonably requested by Stripe. Stripe may have an obligation to provide certain notices or forms, such as tax invoices, to Connected Accounts. You must ensure that Your User Agreement enables you to receive such notices and forms on the Connected Accounts’ behalf, without Stripe being obliged to directly provide the notices and forms to the Connected Accounts, and you must promptly make such notices and forms available to your Connected Accounts in a manner consistent with applicable law.

e. Right to Amend: Stripe may amend this Connect Platform Agreement upon notice to you, which may be provided through email, your Stripe dashboard, and/or Stripe’s web site. You agree that any changes to this Connect Platform Agreement will be binding on you 7 days after the amendment is made by Stripe (or, if a longer period is required by applicable law, such longer period). If you elect to not accept the changes to this Connect Platform Agreement, you must (a) provide notice to Stripe and (b) immediately cease using Stripe Connect. Where you do not provide such notice prior to the amendments becoming binding, by continuing to use the Services you agree that you are consenting to any such changes to the Connected Account Agreement.

f. Assignment: You may not assign or attempt to assign this Connect Platform Agreement without the express consent of Stripe in advance.

g. Entire Agreement: This Connect Platform Agreement constitutes the entire agreement between you and Stripe with respect to Stripe Connect. These terms and conditions describe the entire liability as between you and Stripe, and set forth your exclusive remedies, with respect to Stripe Connect. If any provision of this Connect Platform Agreement (or portion thereof) is held to be invalid or unenforceable under applicable law, then it should be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.

Thank you and welcome to Stripe Connect!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
